language: node_js

node_js:
  - '9'
  - '8'
  - '7'

before_install:
  - 'nvm install-latest-npm'

cache:
  yarn: true
  directories:
    - $HOME/.npm

install:
  - yarn install
script:
  - yarn test
