language: node_js

node_js:
  - 'stable'

before_install:
  - 'nvm install-latest-npm'

cache:
  yarn: true
  directories:
    - $HOME/.npm

install:
  - yarn install
script:
  - yarn lint
  - yarn test:coverage
  - cat ./coverage/lcov.info | coveralls
